set shell=/bin/sh
set expandtab
set wildmenu

set tabstop=2
set laststatus=2
set shiftwidth=2
set term=screen-256color

filetype plugin indent on
filetype plugin on

syntax enable

call plug#begin('~/.vim/plugged')

Plug 'danielwe/base16-vim'
Plug 'powerline/powerline', { 'rtp': 'powerline/bindings/vim' }
Plug 'pearofducks/ansible-vim'
Plug 'kovetskiy/sxhkd-vim'
Plug 'fatih/vim-go'
Plug 'nsf/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }
Plug 'mikewest/vim-markdown'
Plug 'dag/vim-fish'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

call plug#end()

function! s:tig_status()
  cd `git rev-parse --show-toplevel % | head -n 1`
  !tig status
endfunction

map <C-G> :TigStatus<CR><CR>
command! TigStatus call s:tig_status()

autocmd BufNewFile,BufReadPost *.md set filetype=markdown

if &shell =~# 'fish$'
  set shell=sh
endif

" let base16colorspace=256  " Access colors present in 256 colorspace

" colorscheme zellner
" less readable on twilight coloured theme .. :-(
" colorscheme base16-twilight
" colorscheme base16-default

" enable modelines for easier use might be a risk I know ;-)
set modeline
set modelines=5

if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif
