test -s ~/.alias && . ~/.alias || true

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export PATH="$PATH:/home/mma/.local/bin"

# Fancy prompt
[ -n "$PS1" ] && export PS1=$'\[\033[38;5;14m\]\u\[\033[38;5;15m\]@\[\033[38;5;3m\]\h\[\033[38;5;15m\] \w \ue602 \[$(tput sgr0)\]'

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && [ -s "$BASE16_SHELL/profile_helper.sh" ] && eval "$("$BASE16_SHELL/profile_helper.sh")"
