#!/usr/bin/env sh

export SXHKD_SHELL='/usr/bin/sh' 
export TERMINAL='/usr/bin/urxvt'
#export PATH="$PATH:~/.config/lemonbar/"

test -x /usr/bin/sxhkd && /usr/bin/sxhkd &
test -x /usr/lib/polkit-gnome-authentication-agent-1 && /usr/lib/polkit-gnome-authentication-agent-1 &
test -x /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
test -x /usr/bin/nitrogen && /usr/bin/nitrogen --restore
test -x /usr/bin/feh && /usr/bin/feh --bg-scale --randomize ~/.config/bspwm/backgrounds/ -Z

sleep 1

test -x /usr/bin/compton && /usr/bin/compton &
test -x /usr/bin/kalu && /usr/bin/kalu &
test -x /usr/bin/nm-applet && /usr/bin/nm-applet &
test -x /usr/bin/package-update-indicator && /usr/bin/package-update-indicator &
test -x /usr/bin/clipit && /usr/bin/clipit &
test -x /usr/bin/conky && /usr/bin/conky -c ~/.config/conky/conky.conf &
test -x /usr/bin/conky && /usr/bin/conky -c ~/.config/conky/conky-shortcuts.conf &
test -x /usr/bin/xautolock && /usr/bin/xautolock -time 10 -locker 'xlock -mode blank' &

if [ -x /usr/bin/tickr ]; then
  # more padding now because tickr need some space
  bspc config top_padding 40
  /usr/bin/tickr &
fi

test -x /usr/bin/tilda && /usr/bin/tilda -h &

# Panel
if [ -x /usr/bin/lemonbar ]; then
  test -x $HOME/.config/lemonbar/simplepanel && $HOME/.config/lemonbar/simplepanel &
elif [ -x /usr/bin/polybar ]; then
  test -x $HOME/.config/polybar/launch.sh && $HOME/.config/polybar/launch.sh &
fi

if [ -f $HOME/.bspwm_autostart ]; then
  . $HOME/.bspwm_autostart
fi
