#!/usr/bin/env sh

export SXHKD_SHELL='/usr/bin/sh' 
export TERMINAL='/usr/bin/urxvt'

test -f /usr/bin/sxhkd && /usr/bin/sxhkd &
test -f /usr/lib/polkit-gnome-authentication-agent-1 && /usr/lib/polkit-gnome-authentication-agent-1 &
test -f /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
test -f /usr/bin/nitrogen && /usr/bin/nitrogen --restore
test -f /usr/bin/feh && /usr/bin/feh --bg-scale --randomize ~/.config/bspwm/backgrounds/ -Z
  #/usr/bin/feh --bg-center ~/.config/bspwm/background.jpg

sleep 1

test -f /usr/bin/compton && /usr/bin/compton &
test -f /usr/bin/kalu && /usr/bin/kalu &
test -f /usr/bin/nm-applet && /usr/bin/nm-applet &
test -f /usr/bin/clipit && /usr/bin/clipit &
test -f /usr/bin/conky && /usr/bin/conky -c ~/.config/conky/conky.conf &
test -f /usr/bin/conky && /usr/bin/conky -c ~/.config/conky/conky-shortcuts.conf &
test -f /usr/bin/xautolock && /usr/bin/xautolock -time 10 -locker blurlock &

# Panel
test -f $HOME/.config/polybar/launch.sh && $HOME/.config/polybar/launch.sh
#test -f $HOME/.config/dzen2/panel_dzen2 && $HOME/.config/dzen2/panel_dzen2 &
#test -f $HOME/.config/lemonbar/panel && $HOME/.config/lemonbar/panel &
