#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config initial_polarity second_child

bspc config border_width         	1
bspc config window_gap          	3

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	false

bspc config normal_border_color 	"#1f1d21"
bspc config focused_border_color 	"#a50000"
bspc config presel_feedback_color 	"#333333"

# padding
bspc config bottom_padding 	2
bspc config top_padding 		46
bspc config left_padding 		2
bspc config right_padding 	2

# allow moving around with floated window
bspc config pointer_modifier mod1
bspc config click_to_focus  true
bspc config pointer_action1 focus
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_action3 none

# monitor detection
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# specific app rules
bspc rule -a Steam desktop=^3 follow=on split_dir=right
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:mutt desktop=^2 follow=on
bspc rule -a URxvt:weechat desktop=^2 follow=on
bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a URxvt:vpn desktop=^5 follow=on state=floating
bspc rule -a URxvt:upass state=floating
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a feh floating=on manage=off
bspc rule -a Firefox floating=on state=floating manage=on

# special rule for pinentry thingy
bspc rule -a '*:pinentry' follow=on state=floating
bspc rule -a '*:pinentry-gtk-2' follow=on state=floating

# tile emacs-gtk
bspc rule -a Emacs state=tiled

xdotool search --onlyvisible --name tilda windowfocus

. $HOME/.config/bspwm/autostart
