#!/usr/bin/env sh

export BSPWM_HOME=$(readlink -f $(dirname $0)/)
export BSPWM_STATE=$HOME/.bspwm.state

if [ -e $BSPWM_STATE ]; then
  bspc wm --load-state "$BSPWM_STATE"
  rm "$BSPWM_STATE"
else
  bspc wm -o

  bspc monitor -d 1 2 3 4 5 6 'Todo' 'Emacs' 'Firefox'

  bspc config initial_polarity second_child

  bspc config border_width         	2
  bspc config window_gap          	1

  bspc config split_ratio          	0.50
  bspc config borderless_monocle   	true
  bspc config gapless_monocle      	true
  bspc config focus_follows_pointer	false

  bspc config normal_border_color 	"#1f1d21"
  bspc config focused_border_color 	"#a50000"
  bspc config presel_feedback_color 	"#333333"

  # padding
  bspc config bottom_padding  2
  bspc config top_padding     24
  bspc config left_padding    2
  bspc config right_padding   2

  # allow moving around with floated window
  bspc config pointer_modifier mod1
  bspc config click_to_focus  true
  bspc config pointer_action1 focus
  bspc config pointer_action1 move
  bspc config pointer_action2 resize_corner
  bspc config pointer_action3 none

  # monitor detection
  bspc config remove_disabled_monitors true
  bspc config remove_unplugged_monitors true

  # specific app rules
  #bspc rule -a feh floating=on manage=off

  # Firefox rules
  bspc rule -a 'Firefox:*' state=floating follow=on
  bspc rule -a 'Firefox:Navigator' desktop=^9 state=tiled follow=on

  # tile emacs-gtk
  bspc rule -a 'Emacs:emacs' state=tiled follow=on desktop=^8
  bspc rule -a 'Emacs:emacs-gtk' state=tiled follow=on desktop=^8

  # OpenTodoList (https://github.com/mhoeher/opentodolist/releases)
  bspc rule -a 'OpenTodoList:OpenTodoList' manage=on state=tiled follow=off desktop=^7

  # Guake rule
  #bspc rule -a '*:guake' follow=on state=floating

  # Tilda rule
  bspc rule -a 'Tilda:tilda' follow=on state=floating manage=on sticky=on

  bspc config external_rules_command "$BSPWM_HOME/external_rules"

  . $BSPWM_HOME/autostart
fi
