#!/usr/bin/env sh

set -ex

case $1 in
	desktop-add)
		name="$(zenity --entry --text='Type the name of the new workspace:')"
		bspc monitor -a "$name"
	;;
	desktop-remove)
		name="$(bspc query -D --names | zenity --list --column Workspaces --text="Select the workspace you want to remove" --hide-header)"
		bspc desktop "$name" -r
	;;
	move-to-desktop)
		name="$(bspc query -D --names | zenity --list --column Workspaces --text="Move to workspace:" --hide-header)"
		bspc node -d "$name"
		bspc desktop -f "$name"
	;;
	desktop-rename)
		name="$(zenity --entry --text='Rename the current workspace to:')"
		bspc desktop -n "$name"
	;;
	desktop-swap)
		name="$(bspc query -D --names | zenity --list --column Workspaces --text="Swap with:" --hide-header)"
		bspc desktop -s "$name"
	;;
	move-next-empty-desktop)
		name="$(bspc query -m -d next.!occupied -D --names)"
		bspc node -d "$name"
		bspc desktop -f "$name"
	;;
esac
