#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a "*" split_dir="east"

bspc config border_width         	1
bspc config window_gap          	3

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc config normal_border_color 	"#1f1d21"
bspc config focused_border_color 	"#a50000"
bspc config presel_feedback_color 	"#be5e1e"

# padding
bspc config bottom_padding 		0
bspc config top_padding 		0
bspc config left_padding 		0
bspc config right_padding 		0

bspc rule -a Steam desktop=^3 follow=on split_dir=right
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:mutt desktop=^2 follow=on
bspc rule -a URxvt:weechat desktop=^2 follow=on
bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a URxvt:vpn desktop=^5 follow=on state=floating
bspc rule -a URxvt:upass state=floating
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a feh floating=on manage=off

# special rule for pinentry thingy
bspc rule -a '*:pinentry' follow=on state=floating

xdotool search --onlyvisible --name tilda windowfocus

. $HOME/.config/bspwm/autostart
