#!/usr/bin/env bash

PANEL_FIFO=/tmp/panel-$USER-fifo

FG_COLOR='#cdc5b3'
BG_COLOR='#0e0e0e'

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

xtitle -sf 'Title;%s\n' > "$PANEL_FIFO" &
conky -c $HOME/.config/dzen2/conky/01.lua > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &
